### ISSUE TITLE
Periodic Backups

### ISSUE THREAD

**Issue by Web3Slimchance** [IndexerDAO/IndexerDAO#17]

**Comment by alex-pakalniskis** [comment]
https://discord.com/channels/1015335996587511921/1015335997514469408/1026019467647524934
* Vince chatting with Don about his backup set up

**Comment by alex-pakalniskis** [comment]
I feel like it could benefit us to backup our Project board too. 

Query GitHub API for project board issues, save a daily snapshot (compressed) and keep a few days of backups just in case. 

I have experience with GitHub API contents endpoint so I could whip something up pretty quickly if we decide to follow through.

**Comment by alex-pakalniskis** [comment]
Note from Dylan: investigate Radicle

**Comment by alex-pakalniskis** [comment]
Can re-open when we're out of MIPs QA mode and more into "regular" production indexing
