### ISSUE TITLE
Timetracker

### ISSUE THREAD

**Issue by Web3Slimchance** [IndexerDAO/IndexerDAO#28]

**Comment by alex-pakalniskis** [comment]
is this something we'd want public?

**Comment by alex-pakalniskis** [comment]
predetermine value of contributions to DAO (set price based on value provided and not time-based)
* no benefit to being slow
* hard to predict length of certain tasks

VS

hourly-rate for contribution

**Comment by alex-pakalniskis** [comment]
# TODO

1. Agree on hours for initial projects

2. Set a project lead for each of the initial projects
  1. contributions are tracked in the Excel sheet
  2. Project status is updated in the GitHub Project board
