### ISSUE TITLE
Announce new DAO members

### ISSUE THREAD

**Issue by Web3Slimchance** [IndexerDAO/IndexerDAO#32]
# Options
* Single post for Vince and Payne
* Separate post for Vince and Payne

We could just post it during our weekly Sunday meeting

**Comment by alex-pakalniskis** [comment]
IndexerDAO would like to welcome Vince from Nodeify to the MIPs Operator team!

Vince brings community support and production indexing experience to the DAO. His recent Learning Series workshop about Indexing 101 was full of pro-tips and he's just a great guy, so we're thrilled to see what the future holds with Vince on the team.



---


IndexerDAO would like to welcome Payne from Stake Squid to the MIPs Operator team!

Payne brings additional community support and production indexing experience to the DAO. His docker-compose up configurations and documentation are widely used by indexers and he's a great mentor in the community. We're excited to see what comes next with Payne on the team.
