### ISSUE TITLE
Phase 0 Typeform

### ISSUE THREAD

**Issue by Web3Slimchance** [IndexerDAO/IndexerDAO#33]

**Comment by Web3Slimchance** [comment]
- [ ]  Goerli Ethereum Address of your Indexer? 
- [ ]  Graph-node endpoint?This question is required. *
- [ ]  Prometheus endpoint?This question is required. *
- [ ]  Any additional consideration that we should have to reach your endpoints? This question is required.* i.e. credentials, please include username and password auth for Prometheus

**Comment by alex-pakalniskis** [comment]
@Web3Slimchance did Payne have the endpoint information you needed?

**Comment by Web3Slimchance** [comment]
Phase 0 typeform was completed and submitted
