### ISSUE TITLE
Mission, Vision and Values

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/IndexerDAO#5]
## Mission

- A DAO to support aspiring and active indexers with on-going education and project-based learning opportunities.
- To support innovation in the indexing space by testing R&D efforts from core developers

## Vision

- To become a DevOps talent incubator for The Graph and broader web3 ecosystem.
- To be the vanguard of the Indexer Community.

## Values 

- Empowerment
- Continuous learning
- Integrity
- Open-mindedness / respect

**Comment by alex-pakalniskis** [comment]
@Web3Slimchance could you please add the values we all agreed upon the above comment?

**Comment by Web3Slimchance** [comment]
Added. We may want to expand a bit on the values if we display them on our webapp🙏
