### ISSUE TITLE
DAO Architecture Diagram

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/IndexerDAO#58]

**Comment by dylviz** [comment]
![Image](https://user-images.githubusercontent.com/25091990/194775708-90be1bc6-2392-43f5-9026-20ebd94388a7.png)

**Comment by alex-pakalniskis** [comment]
# A fork in the road

## MIPs as another DAO task and not a central mission that all can join (limited spaces like all projects)

## MIPs as core track for anyone (and incentivize all DAO members to provide value)

## Hybrid model

**Comment by alex-pakalniskis** [comment]
# Projects

## MIPs
Project lead: Slim 

## Compliance Framework
Advisor: Jim

## Nameless Shipping
Project lead: Dylan

**Comment by alex-pakalniskis** [comment]
@dylviz are you still working on this?

**Comment by dylviz** [comment]
> @dylviz are you still working on this?

I think it can be closed. Unless we want another iteration. We can always do another way
