### ISSUE TITLE
Adding Channon to the DAO

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/IndexerDAO#87]

**Comment by Web3Slimchance** [comment]
Channon was voted into the DAO on Jan 23. 
- [x] Give Channon access to all channels in Discord
- [x] Discord announcement
- [x] Twitter announcement
- [x] Onboarding

**Comment by alex-pakalniskis** [comment]
@dylviz could you post to the Twitter? I don't have the login cached on my web app anymore lol.

Here's the text from Discord:
> IndexerDAO would like to welcome Channon to the MIPs Operator team!!!
> 
> Channon brings a background in community development and engineering to the DAO. She's already diving in and contributing to our Graphcast quality assurance testing and is looking forward to supporting our efforts around indexer education. We're pumped to see what the future holds with Channon on the team.
